### ISSUE TITLE
error when running mvn install

### ISSUE THREAD

**Issue by brianlucas** [RetailMeNot/SeleniumGridScaler#13]
Hi, I'm experimenting with this and seeing the following error when running `mvn install`:

```
Jun 19, 2015 23:30:27:894 PM - INFO  [main] [AwsVmManager] Setting fallback subnet: foo
Jun 19, 2015 23:30:27:894 PM - ERROR [main] [AwsVmManager] Insufficient capacity in subnet [foo]: com.amazonaws.AmazonServiceException: message (Service: null; Status Code: 0; Error Code: InsufficientInstanceCapacity; Request ID: null)
Jun 19, 2015 23:30:27:894 PM - INFO  [main] [AwsVmManager] Setting fallback subnet: foo
Jun 19, 2015 23:30:27:894 PM - ERROR [main] [AwsVmManager] Insufficient capacity in subnet [foo]: com.amazonaws.AmazonServiceException: message (Service: null; Status Code: 0; Error Code: InsufficientInstanceCapacity; Request ID: null)
Jun 19, 2015 23:30:27:900 PM - INFO  [main] [AwsVmManager] Falling back to IAM roles for authorization since no credentials provided in system properties
java.lang.IllegalArgumentException: AWS Access Key must be passed in by the [awsAccessKey] system property or be present in the AWS config file
    at com.rmn.qa.aws.AwsVmManager.getCredentials(AwsVmManager.java:158) ~[classes/:na]
    at com.rmn.qa.aws.AwsVmManager.<init>(AwsVmManager.java:91) ~[classes/:na]
    at com.rmn.qa.aws.VmManagerTest.testClientInitialized(VmManagerTest.java:606) [test-classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.8.1.jar:na]
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.8.1.jar:na]
```

I am guessing I need to download and install selenium grid?  If so, is it the same package listed here?

http://selenium-release.storage.googleapis.com/index.html?path=2.46/

The README mentions automation-grid, but I'm guessing it's selenium-server in the download link above.

**Comment by mhardin** [comment]
This should not be happening when attempting to build the project.  I am not able to reproduce this issue when running 'mvn clean install'

**Comment by brianlucas** [comment]
here's the relevant gist:
https://gist.github.com/brianlucas/f234105fe3b611dbbfcf

I saw you had an AMI you were able to share.  Not sure if this is dependent on the OS or other configuration values, I'm using a basic bootstrap Amazon EC2 API here.

**Comment by mhardin** [comment]
It looks like a test is failing:
```
Failed tests:   testShutdown(com.rmn.qa.task.AutomationReaperTaskTest): Node should be terminated as it was empty
```

Seems we should figure out why this test is failing on your machine and fix the test.  If you have time, feel free to investigate this and submit a pull request.  If you build the jar locally and then deploy it to your EC2 machine, you should be good to go in the mean time.

**Comment by brianlucas** [comment]
I'll try with a different distro in the next few days and see if I can isolate cause.
